pipelines:
  branches:
    development:
     - step:
         name: Build to Test
         script:
            - yarn install
            - yarn build

     - step:
         name: Deploy to production
         deployment: production
         script:
           - echo "Deploying to production environment"
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'root'
               SERVER: '137.184.53.72:3001'
               COMMAND: '/home/deploy.sh'